name: Meshery-Operator Build and Releaser
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker edge build & push
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push \
            --no-cache \
            -t ${{ secrets.IMAGE_NAME }}:edge-latest \
            -t ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_SHA::7} \
            .
      - name: Docker stable build & push
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push \
            --no-cache \
            -t ${{ secrets.IMAGE_NAME }}:stable-latest \
            -t ${{ secrets.IMAGE_NAME }}:stable-${GITHUB_REF/refs\/tags\//} \
            -t ${{ secrets.IMAGE_NAME }}:stable-${GITHUB_SHA::7} \
            .
#       - name: Docker Hub Description
#         if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
#         uses: peter-evans/dockerhub-description@v2.0.0
#         env:
#           DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#           DOCKERHUB_REPOSITORY: ${{ secrets.IMAGE_NAME }}
